### ISSUE TITLE
actually found UNIMPLEMENTED

### ISSUE THREAD

**Issue by Sato-Kimura** [phiSgr/gatling-grpc#10]
My code:
class GrpcExample extends Simulation {

  val grpcConf = grpc(ManagedChannelBuilder.forAddress("localhost", 9002).usePlaintext())
  val request  = registerRequest.newBuilder().setUsername("Kimura").build();
  val s = scenario("Example")
    .exec(
      grpc("registerGreet")
        .rpc(GreetServiceGrpc.METHOD_REGISTER_GREET)
        .payload(request)
    )
    .exitHereIfFailed
  setUp(
    s.inject(constantUsersPerSec(1) during (1 seconds))
  ).protocols(grpcConf)
}
My server uses java code: 
Server server = ServerBuilder.forPort(9002)
                .addService(new GrpcServiceIml()).build();
        System.out.println("Starting server...");
        server.start();
        System.out.println("Server started!");
        server.awaitTermination();

[ERROR]: grpcStatusCode.find.is(OK), but actually found UNIMPLEMENTED

**Comment by phiSgr** [comment]
I am not very sure about the cause of your problem.

What I do feel weird is that while `request` is a Java protobuf object, you used it with `GreetServiceGrpc.METHOD_REGISTER_GREET`, a method descriptor generated by ScalaPB. The test should not compile but seemingly it does.

BTW, injecting many short-lived virtual users to make one gRPC request is very costly if you do not enable channel sharing.

**Comment by Sato-Kimura** [comment]
Because I use maven project and compile the .proto file.

**Comment by phiSgr** [comment]
Even if you use Maven instead of sbt, I fail to see how the `ReqT` of `METHOD_REGISTER_GREET` matches the type of `request`. Quoting ScalaPB:

> ScalaPB generates case classes that can co-exist in the same project alongside the Java-generated code for ProtocolBuffer. 
> ...
> the ScalaPB generated code use the proto file as part of the package name (in contrast to Java which uses the file name in CamelCase as an outer class)

Could you look into the generated Scala and Java code, and tell me their fully qualified class names?

**Comment by Sato-Kimura** [comment]
this my source :
https://github.com/Sato-Kimura/grpc-example.git
Please see help me

**Comment by phiSgr** [comment]
So I have mistaken. The `METHOD_REGISTER_GREET` descriptor is not from ScalaPB, but a really old version of grpc-java.

My code is not designed to work with generated protobuf Java classes. You lose the extraction and modification capability powered by the ScalaPB lenses.
That said, your test in its current form should work.

Could you confirm that, in your server, you have overridden the `registerGreet` method in your `GrpcServiceIml`<sup>1</sup> class? We all get silly sometimes.

---
1. I think you missed the "p" in "Impl".

**Comment by Sato-Kimura** [comment]
Sorry I missed the "p" in "Impl" butBut it does not affect.
https://gyazo.com/9c1b05a74257b9c69cc1f3a46e242d1f
My server is still working normally, I tested it when I wrote a client using java. The client and server results are normal.

**Comment by phiSgr** [comment]
Are the proto files exactly the same? Especially the package, service and method names, as they are case-sensitive.

**Comment by Sato-Kimura** [comment]
Yes, 2 the proto files exactly the same. I'm sure about that

**Comment by phiSgr** [comment]
I just cloned your test repository and I cannot reproduce your problem.
I cannot provide any more help without your server code.

**Comment by Sato-Kimura** [comment]
My source server:
https://github.com/Sato-Kimura/grpc-server.git

using spring boot project

**Comment by phiSgr** [comment]
https://github.com/Sato-Kimura/grpc-server/blob/82f449f2dcc163c08ddd99147131a684ae39b982/src/main/proto/Greet.proto#L3
https://github.com/Sato-Kimura/grpc-example/blob/73ba1302d529c4de2bed3a8871e31ad2bd1c704e/src/main/proto/Greet.proto#L3

> Are the proto files exactly the same? Especially the **package**, service and method names, as they are case-sensitive.

I am disappointed.

**Comment by Sato-Kimura** [comment]
Sorry, Thanks you.
