### ISSUE TITLE
Support for sharing a single (n) channel

### ISSUE THREAD

**Issue by yeenow123** [phiSgr/gatling-grpc#14]
I'm trying to run a load test, however with both `atOnceUsers` and `constantUsersPerSec` I see new connections being created throughout the execution of the gatling load test.  I am using `shareChannel` as well.  Is there anyway to use a single gRPC channel or support a configurable amount?

**Comment by phiSgr** [comment]
From what observations do you think multiple gRPC channels are created?

**Comment by yeenow123** [comment]
I'm looking at the number of TCP connections via `netstat -an | grep $PORT | wc -l` while the load test is running.  It grows up to the total users in the test sometimes

**Comment by phiSgr** [comment]
Could you share your test code?

**Comment by yeenow123** [comment]
I had to rename a few things (code doesn't compile) and unfortunately can't share the proto.

But here's pretty much what it looks like.  It seems like a channel is being created for each new virtual user.

```
class BasicSimulation extends Simulation {

  val grpcConfig = grpc(
    ManagedChannelBuilder
      .forAddress("localhost", 8084)
      .usePlaintext()
  ).shareChannel

  val feeder = Iterator.continually(
    Map("id" -> (Random.nextInt(5) + 1).toString,
        "otherId" -> Random.alphanumeric.take(16).toString())
  )

  val scn = scenario("basic")
    .feed(feeder)
    .exec {
      s =>
        grpc("single-request")
          .rpc(TestGrpc.getQueryMethod)
          .payload(IdRequest
            .newBuilder()
            .setOtherId(s("otherId").as[String])
            .setId(s("id").as[String])
            .setBody("Hello.")
            .build())
          .check(statusCode is Status.Code.OK)

        s
    }

  setUp(
    scn.inject(
      constantConcurrentUsers(50) during(30 seconds))
//      atOnceUsers(10))
//      .throttle(
//        reachRps(50) in (0 seconds),
//        holdFor(30 seconds)
//      )
    protocols(grpcConfig)

  )
}
```

**Comment by phiSgr** [comment]
First, `shareChannel` already make the virtual users share one single channel. Running `sbt 'gatling:testOnly com.github.phisgr.example.ThrottleExample'`, I see only one connection. Removing `shareChannel` I see as many as the virtual users.

Additionally, creating actions in the `.exec` block should [do nothing at all](https://gatling.io/docs/current/general/scenario/#exec).
You may have made a mistake when you erased your sensitive information. 

I don't think I can reproduce your problem.

**Comment by yeenow123** [comment]
It seems to be the issue with my `feeder`.  It seems as if I define an infinite feeder with `Iterator.continually` it has this behavior.  The moment I remove the feeder and hard-code the value it uses a single connection.

Still relatively new to gatling and trying to define a feeder and use the correct DSL, the expression `${STRING}` api doesn't doesn't seem to work for me

**Comment by yeenow123** [comment]
I think your following comment may be an issue for me as I am using the generated Java protobuf code.

https://github.com/phiSgr/gatling-grpc/issues/10#issuecomment-497205741

I am using gradle and the gradle scalapb plugin is pretty outdated, but I'll give it a shot.

**Comment by phiSgr** [comment]
The guessing from both of us is counterproductive. I know there is stuff that you cannot post publicly. I suggest you send me an email with all the details so that I can help.
