### ISSUE TITLE
How to extract the values from the gRPC response?

### ISSUE THREAD

**Issue by yeenow123** [phiSgr/gatling-grpc#16]
I apologize as this is more of a question, but couldn't find your email.

I'm trying to extract values from the gRPC response to further pass on and make more requests but can't seem to find an example how.

**Comment by yeenow123** [comment]
And just as I asked the medium article came to the rescue

https://medium.com/@georgeleung_7777/a-demo-of-gatling-grpc-bc92158ca808

**Comment by phiSgr** [comment]
I did spend some effort to make sure there are answers if one digs hard enough. :)

**Comment by phiSgr** [comment]
More examples in the tests.

https://github.com/phiSgr/gatling-grpc/blob/ce6c040f9e49b4df88f946789f56aa0a77f47f60/src/test/scala/com/github/phisgr/example/GrpcExample.scala#L38
