### ISSUE TITLE
Documentation: how to manage complex proto types with lists and embedded objects

### ISSUE THREAD

**Issue by unludo** [phiSgr/gatling-grpc#19]
Hi,
I have difficulty creating tests as my grpc api is a bit complex. I have a grpc method with input type looking like:

```
message RequestFilter {
    uint32 offset = 1;
    uint32 limit = 2;
    bool oroperation = 3;
    repeated Filter filters = 4;
}
message Filter {
    string name = 1;
    string value = 2;
    string operand = 3;
}
```
Could you please help me put data from the session in a filter? As there is a Seq, I don't see how to use _lenses_ and _updateExpr_.
If you are ok, I could help update the doc to show how to do this.

Thanks!

**Comment by phiSgr** [comment]
I almost dismissed this as a question. Turns out we need the `Expression` version of the methods in `SeqLikeLens` to do it cleanly. I will update it soon.

**Comment by phiSgr** [comment]
@unludo Feel free to do a write-up referring to the examples in the tests.

**Comment by unludo** [comment]
@phiSgr thanks a lot! I will do next week.
