### ISSUE TITLE
Pass multiple channels to the GrpcProtocol

### ISSUE THREAD

**Issue by zupalex** [phiSgr/gatling-grpc#24]
**Is your feature request related to a problem? Please describe.**
HttpProtocol offer a way to pass multiple URLs and then each generated user will pick a random URL from that list. It doesn't seem possible with gatling-grpc. This is useful when testing a setup with multiple Grpc servers not sitting behind a proxy and which a client balanced.

**Describe the solution you'd like**
 It would be good to be able to pass a list of channels to the GrpcProtocol and have GrpcComponent getChannel method pick one from the list randomly.

**Describe alternatives you've considered**
Tried to see if I could create my own Protocol without having to duplicate the whole code but did not figure out a smart way to do that.

**Comment by phiSgr** [comment]
Have you considered using a [`NameResolver.Factory`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#nameResolverFactory-io.grpc.NameResolver.Factory-) that resolves to the multiple servers?

**Comment by zupalex** [comment]
Hello, thanks for answering.
I was not aware of this, thanks for pointing it out. It probably does the job. I'll try it out.

**Comment by phiSgr** [comment]
@zupalex could you let me know if that worked? It would be great to have a working snippet.

**Comment by zupalex** [comment]
Hello,

sadly I did not get it to work. This feature is half deprecated, half experimental.

Thanks,
Alex

**Comment by thinkerou** [comment]
hi @phiSgr I want to use like this:
```
class TestSimulation extends Simulation {
  
    // ...
    MyRpcClient myRpcClient =MyRpcClient.create("serviceName");
    HelloRequest req = HelloRequest.newBuilder().build();
    exec(
        grpc("myGrpcTest")
       .call(myRpcClient, "methodName")
       .payload(req.toByteString())
    )
    // ...
}
```

if I don't use gatling, I will use the follow way to call my multi grpc services:
```
public class MyTest {

    MyRpcClient myRpcClient =MyRpcClient.create("serviceName");

    HelloRequest req = HelloRequest.newBuilder().build();

    MyRpcResponse res = myRpcClient.call(MyRpcRequest.newBuilder()
                    .setRawRequest(req.toByteString())
                    .setFullMethodName("methodName")
                    .build())
}

```
