### ISSUE TITLE
Issue with SSL

### ISSUE THREAD

**Issue by unludo** [phiSgr/gatling-grpc#31]
I have an issue with SSL. I have a scala client which works in ssl but when I use the same code for initializing the gatling-grpc  configuration, the test fails with the message:
`Could not get key uri: UNAVAILABLE: io exception`

Here is the code I use for initializing the channel:

```
  val sslContext: SslContext = GrpcSslContexts.forClient.build() 
  private val conf = NettyChannelBuilder.forAddress(publicUrl, 443).sslContext(sslContext)
  private val grpcConf:GrpcProtocol = grpc(conf)
```
This code works with my scala client:
```
  val sslcontext = GrpcSslContexts.forClient().build();
  val channel = NettyChannelBuilder.forAddress(host, port).sslContext(sslcontext).build()
```

Here is the log file, including grpc traces, there is no call to the network it seems.
[error.log](https://github.com/phiSgr/gatling-grpc/files/4845539/error.log)

Do you have an idea of what the issue could be?

Thank you 
Ludovic

**Comment by phiSgr** [comment]
Try downgrading to Java 8 to run the test.

**Comment by phiSgr** [comment]
You may get a better looking error when you set `shareChannel` for the `GrpcProtocol`.

**Comment by unludo** [comment]
Thanks a lot for the advice, the issue was somewhere else and I found thanks to the debug session and the place you indicated.

**Comment by phiSgr** [comment]
It would be helpful if you can state the error you encountered.

**Comment by unludo** [comment]
Ok. My simulation connects to 2 endpoints, one in ssl, the other not.
The second one was in fact malfunctioning.
But because of the generic error message in stdout (the origin of the error is not forwarded up/displayed), I was believing the issue was coming from the ssl endpoint.
An improvement would be to improve the logging / error management system.
