### ISSUE TITLE
Conflicts with Scala 12.2 vs 12.3 versions for grpc and gatling3.**

### ISSUE THREAD

**Issue by pavannarrasdet** [phiSgr/gatling-grpc#32]
**Describe the bug**
When Scala version is set to 2.12/2.12.10 i am getting below error while compiling the project
package scalapb.grpc is not a value
    grpc("request_1")
package scalapb.grpc is not a value
  val grpcConf = grpc(ManagedChannelBuilder.forAddress("photoslibrary.googleapis.com",443))

If i set to 2.13/2.13.1 the project is compiling successfully but the engine class is failing to run the program and throwing runtime error

**To Reproduce**
Clone below repo and compile and execute ( please change OS name at plugin artifact per your OS) , however i have also pushed target folder to ensure the profobuffer generated class files are accessible

**Expected behavior**
i am expecting to compile gRPC libraries with Scala2.12 version instead of 2.13 so that the engine class should be able to run the gatling program and execute TestGRPC simulation

**Environment:**
 - OS: linux/Unix(Docker)
 - Java: Java8
 

**Additional context**
Please find my [repo](https://github.com/pavannarrasdet/scalaPBWithMavenExample) here 
I have done many trail and errors and confirming the issue with scala version conflicts

**Comment by phiSgr** [comment]
Don't name your package `scalapb`, you're begging name clashes to happen.

**Comment by pavannarrasdet** [comment]
You are an awesome Guy ! it worked .. i am closing the issue
