### ISSUE TITLE
Using gatling-grpc as tool

### ISSUE THREAD

**Issue by obvionaoe** [phiSgr/gatling-grpc#34]
Hi, would it be possible to use gatling-grpc with gatling being used as a cli tool instead of the code based approach?

**Comment by phiSgr** [comment]
What do you mean by a CLI tool?

I believe my library can be used with the [Gatling bundle](https://gatling.io/docs/current/installation/#using-the-bundle), provided that the protobuf classes are already generated.

---

If you mean no simulation scripts at all, there's no point in using Gatling, and by extension, this library. What Gatling excels at is the logic between requests, needed when you're load testing an **application**.

> Some load testing tools, such as ab or wrk are very efficient at url bashing, but can’t deal with logic between requests.
> Advanced load testing tools such as Gatling can deal with virtual users, each one having its own data and maybe taking a distinct browsing path.

Quoted from [Gatling documentation](https://gatling.io/docs/current/general/concepts/)

This comparison also applies when you compare Gatling-gRPC with a CLI tool like [ghz](https://ghz.sh/).

**Comment by phiSgr** [comment]
Tracked in #37.
