### ISSUE TITLE
Gatling-Grpc fails to load class on the grpc() call

### ISSUE THREAD

**Issue by obvionaoe** [phiSgr/gatling-grpc#35]
**Describe the bug**
Gatling-Grpc fails to load class on the grpc() call

**To Reproduce**
```
package computerdatabase

import com.github.phisgr.gatling.grpc.Predef.grpc
import io.gatling.core.Predef.{stringToExpression => _, _}
import io.gatling.core.session.Expression
import io.grpc.ManagedChannelBuilder

class GrpcExample extends Simulation {
  val x = ManagedChannelBuilder.forTarget("localhost:6565")

  val grpcConf = grpc(x)
}
```

**Expected behavior**
This code snippet should not end up on an error, I think

**Environment:**
 - OS: Manjaro
 - Java: 1.8.0_262
 - Version: 0.8.2

**Additional context**
The scala compiler also fails to recognize most of the functions from the plugin, such as, warmUpCall()

Thanks

**Comment by phiSgr** [comment]
What you reported gave me [nothing to act on](http://www.catb.org/~esr/faqs/smart-questions.html#beprecise). With your [previous question](https://github.com/phiSgr/gatling-grpc/issues/34), I can only guess you are using the Gatling bundle, and didn't put my library JAR in the right place. If this is correct you can post your directory structure (output of `find .`).

**Comment by phiSgr** [comment]
Tracked in #37.
