### ISSUE TITLE
Polling of a gRPC call

### ISSUE THREAD

**Issue by UserNoOne** [phiSgr/gatling-grpc#36]
@phiSgr  I was using gRPC plugin from past few weeks and its really useful

**feature request related to a problem**
I got a requirement to poll a gRPC call in my project and gatling does provide a feature to poll a http call : https://gatling.io/docs/current/http/polling/ but looks like polling accepts only **HttpRequestBuilder**

**the solution I'd like to see**
```
exec(
  polling
    .every(10 seconds)
    .exec(
      grpc("sample call")
        .rpc(ServerStaus.METHOD_STATUS)
        .payload(Status())
     )
)
```

**Please suggest a workaround if any**

**Comment by phiSgr** [comment]
This suggestion makes sense. I will look into it after I upgrade to Gatling 3.4.0.

**Comment by phiSgr** [comment]
See [Gatling-Ext](https://github.com/phiSgr/gatling-ext#polling)

https://github.com/phiSgr/gatling-ext/blob/95473b9205bf0aff4bf7268c7352ac91ff3c3477/src/test/scala/com/github/phisgr/example/LoopingExample.scala#L27
