### ISSUE TITLE
Missing Stream Call Response Times

### ISSUE THREAD

**Issue by UserNoOne** [phiSgr/gatling-grpc#38]
**Describe the bug**
After pulling "0.9.0" plugin version, tested gRPC server streaming call against my backend services. gatling handled successfully but some how gatling reporter missing response time metrics of stream calls 

![image](https://user-images.githubusercontent.com/18657554/95551649-d563f700-0a28-11eb-8cfe-abd5718594f3.png)

**To Reproduce**
Use example mentioned in "com.github.phisgr.example.StreamingExample" and wait for gatling report

**Expected behavior**
Should see response times of server stream calls as well

**Comment by phiSgr** [comment]
Did you specify the `timestampExtractor`?

**Comment by UserNoOne** [comment]
No, I didn't specify. I used something like this
```
.exec(
        grpc("Listen")
          .serverStream(streamName = "my-example")
          .start(StreamerGrpc.SERVER_STREAM) (StreamServer.defaultInstance.withRequestId())
          .header(SessionHeader)($("clientSessionId"))
          .endCheck(statusCode is Status.Code.OK)
      )
```

**Comment by phiSgr** [comment]
What "response time" were you expecting to be logged?

https://github.com/phiSgr/gatling-grpc/blob/2bd10a5d086aa7eb2d203856f924939b5d820b06/src/main/scala/com/github/phisgr/gatling/grpc/stream/TimestampExtractor.scala#L11
Let me know if you have more questions.

**Comment by phiSgr** [comment]
I know I didn't write a friendly manual to tell you to read. So I don't mind this question to be on the issue board.

But here's the thing. You could've posted your own code when you create the issue, then I would directly tell you to use a `timestampExtractor` and explain the idea of one-way latency. Instead you say, to reproduce, use **my own** test. Do you think I haven't looked at its report after writing it?

**Comment by UserNoOne** [comment]
yeah, now understood. apologies for raising as a bug. please close it

Will take care before raising anything in future
