### ISSUE TITLE
Add Client Streaming Support

### ISSUE THREAD

**Issue by Mahesh-Mothukuri** [phiSgr/gatling-grpc#39]
**Is your feature request related to a problem? Please describe.**
Few days back we included latest version of **gatling-grpc** plugin in order to use features of **stream support**, looks like its missing client stream support

**Additional context**
Are there any planes to include client streaming as well. if its not in scope now. please provide some suggestions

**Comment by phiSgr** [comment]
My plan is to add client streaming after bidi and server streaming API received enough feedback and stabilized. But if you need it now, client streaming can be added with a similar API. 

What is your use for client streaming? File upload?
And how do you want to measure its response time? Server message arrival time - last client message sent time?

**Comment by Mahesh-Mothukuri** [comment]
oh I see, Thanks for quick response 
As of now, my use case is to just send time stamp info :). 

response time will be => "Server message arrival time - last client message sent time"

**Comment by Mahesh-Mothukuri** [comment]
For now, added a method similar to ServerSteam [https://github.com/phiSgr/gatling-grpc/blob/master/src/main/scala/com/github/phisgr/gatling/grpc/request/builders.scala#L13](url)
