### ISSUE TITLE
dynamic target

### ISSUE THREAD

**Issue by predmond** [phiSgr/gatling-grpc#40]
I have one grpc call that returns a response containing a host. I need to use this host in a subsequent grpc call. It appears the target method was added for something like this however I do not see how I can set it dynamically. Can the target method be made to accept an `Expression[String]`?

**Comment by phiSgr** [comment]
This is quite interesting. While feasible, a dynamic target has some performance implications.

Could you tell me more about your backend architecture that require such a design?

I would not add this functionality to the design unless I were convinced that this is not a niche use. But I can probably provide a hack messing with the `Session`.

**Comment by predmond** [comment]
The backend is player-vs-player game server. Clients makes a call to the matchmaking service. The matchmaking service finds a server to host the game and returns the address to matched clients. The clients then connect to the game server for the duration of the match.

I can simulate the matchmaking part in gatling but as far as I can tell it's currently not possible to switch to a new grpc protocol with the returned PvP game server address..

**Comment by phiSgr** [comment]
For now you can use the following hack. This requires `.shareChannel` not being used.

```
val channelAttributeName = "gatling.grpc.channel"
val swapChannel: Expression[Session] = { session: Session =>
  val mainChannel = session(channelAttributeName).as[ManagedChannel]
  val target = session("somewhereYouSaved").as[String]
  session
    .set("stash", mainChannel)
    .set(channelAttributeName, managedChannelBuilder(target).build())
}
val swapBack: Expression[Session] = { session: Session =>
  val mainChannel = session("stash").as[ManagedChannel]
  session(channelAttributeName).as[ManagedChannel].shutdownNow()
  session.set(channelAttributeName, mainChannel)
}
```

**Comment by predmond** [comment]
Thank you very much. This seems to do the trick!
