### ISSUE TITLE
Setting deadline for a gRPC call

### ISSUE THREAD

**Issue by UserNoOne** [phiSgr/gatling-grpc#41]
**Is your feature request related to a problem? Please describe.**
Whenever I trigger high amount of server stream gRPC calls towards our server, I'm seeing 
`Server signaled RPC failed  io.grpc.StatusRuntimeException: INTERNAL: context deadline exceeded`

**Describe the solution you'd like**
Is there a way to set deadline for gRPC call in client end, something like this
```
grpc("sample server")
          .serverStream("fetchInfo")
          .start(SampleServerStreamRequest.defaultData)
          .withDeadlineAfter(deadlineMs, TimeUnit.MILLISECONDS)
```

**Comment by phiSgr** [comment]
https://github.com/phiSgr/gatling-grpc/blob/1dc2cf03eb750bd076b9bb96d0378836c831fe90/src/test/scala/com/github/phisgr/example/ThrottleExample.scala#L59

Do you mind creating a PR that documents this capability?

**Comment by UserNoOne** [comment]
Nice! Will try it out first and then make a PR 

Above error is from our backend gRPC server and from gatling end I have below details
`13:56:36.411 [INFO ] c.g.p.g.g.s.ServerStreamCall - Stream 'fetchInfo' failed for user 812: grpcStatusCode.find.is(OK), but actually found INTERNAL`

**Comment by phiSgr** [comment]
Piecing together what you said:

The server you connect to (let's call it `A`) makes another gRPC call to a server `B`. The call from `A` to `B` failed. Server `A` ends Gatling-gRPC's call (calling `onError`) with the exception that ended the call `A->B`.

If server `A` does not propagate its clients deadline to server `B`, nothing can be done with the tests to make it not fail.

---

With all that said, are you sure it's the test's responsibility to make the calls not fail? Are the actual clients gonna be as nice as the load injector to the server?

**Comment by UserNoOne** [comment]
yeah, you are absolutely right (it might be reason). Because our backend is microservice architecture. So, its quite possible to happen.

Its not at all a test responsibility, after all I'm checking by setting up some random deadline to call. Just to confirm is it with high load on server or due to something else. Because few mins back I noticed a timeout error as well for serverStream gRPC call 

`2020-12-09 13:50:37,909  WARN s.d.o.g.i.ExceptionInterceptor - Intercepted exception, transformed to Status{code=UNKNOWN, description=5.seconds, cause=com.twitter.util.TimeoutException: 5.seconds`

**Comment by UserNoOne** [comment]
Even though deadline for stream calls didn't make much sense, as client might receive n number of stream messages from server before RPC gets completed. So, just for some local debugging purpose I approached you

**Comment by phiSgr** [comment]
Have fun debugging a distributed system!

> I have a problem. Let's use Microservices! Now I have 13 distributed problems.

https://softwareengineering.stackexchange.com/a/339234

**Comment by UserNoOne** [comment]
Anyway Thanks for quick response! I was using gRPC plugin from past few months and its really helpful

**Comment by hugebdu** [comment]
@phiSgr any way to set deadline with `gatling-grpc:0.3.0`?
unfortunately have troubles to upgrade to newer version due to `akka`.

**Comment by phiSgr** [comment]
@hugebdu wow you're in a really unfortunate situation.

My first suggestion is to move your load test into a separate project.

The other possibility is to use the old API where you can supply arbitrary code.

```
grpc("use old API")
  .service(WhateverServiceGrpc.stub)
  .rpc(_.withDeadlineAfter(5, SECONDS).yourMethod)(yourPayload)
```

**Comment by hugebdu** [comment]
@phiSgr ended up using client interceptor on channel

```
  val channel: ManagedChannelBuilder[_] = ManagedChannelBuilder
    .forTarget(target)
    .intercept(new DeadlineInterceptor(10.seconds))
    .usePlaintext()
```

thank you anyway!
