### ISSUE TITLE
build doesn't include Scala version (_2.13) in the repo

### ISSUE THREAD

**Issue by michael-read** [phiSgr/gatling-grpc#43]
**Describe the bug**
The following search doesn't show gatling-grpc_2.13:
https://search.maven.org/search?q=g:com.github.phisgr

Used this to resolve:
libraryDependencies += "com.github.phisgr" % "gatling-grpc" % "0.11.1" % "test,it"

Instead of the expected:
libraryDependencies += "com.github.phisgr" %% "gatling-grpc" % "0.11.1" % "test,it"

**Comment by phiSgr** [comment]
This is [intentional](https://github.com/phiSgr/gatling-grpc/commit/02120213583a1c46f96f2a6c58acce9be2175e60#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR4).

**Comment by michael-read** [comment]
certainly a non-standard practice, not to mention your article on Medium:
```
libraryDependencies ++= Seq(
  "io.grpc" % "grpc-netty" % scalapb.compiler.Version.grpcJavaVersion,
  "com.thesamet.scalapb" %% "scalapb-runtime-grpc" % scalapb.compiler.Version.scalapbVersion
)
libraryDependencies += "com.github.phisgr" %% "gatling-grpc" % "0.10.1" % "test,it"
```

**Comment by phiSgr** [comment]
> certainly a non-standard practice

True, but this is not the standard "integrate this library into your application" use-case anyway.

> not to mention your article on Medium

I was kind of depending on https://github.com/phiSgr/gatling-grpc-sbt-demo/pull/1 before reviewing it. I updated it just now.
