### ISSUE TITLE
Call Server Stream Multiple Times With Custom Arguments

### ISSUE THREAD

**Issue by UserNoOne** [phiSgr/gatling-grpc#44]
**Is your feature request related to a problem? Please describe.**
I would like to call same sever stream multiple times by providing following things as unique from a **single gatling virtual user** but current design of establishing server stream not allowing me to do
- stream name (unique for each call)
- response name(used in saving response and useful in combining session)

This is how single server stream looks like
```
def userStatusNotifications(streamName:String="userStatusStream"): ChainBuilder = {
   exec(
        grpc("Get User Status")
          .serverStream(streamName) 
          .start(UserStatusGrpc.METHOD_GET_USER_STATUS)(
            userStatus.defaultInstance.updateExpr(
              _.user:~ $("user")
            ))
          .extract(_.some)(_ saveAs "userStatusResponse")
          .sessionCombiner(SessionCombiner.pick("userStatusResponse"))
          .header(SessionHeader)($("userSessionId"))
          .endCheck(statusCode is Status.Code.OK)
      )
  }
```

**Describe the solution you'd like**
I would like to use "user" session variable value in filling **streamName/StatusResponse** So, that when ever the notification comes, I can vaildate for which user that notification received and proceed further 

```
def userStatusNotifications(streamName:String="StatusStream"): ChainBuilder = {
     exec(
        grpc("Get User Status")
          .serverStream("${user}"+streamName) //unique stream name for each user
          .start(UserStatusGrpc.METHOD_GET_USER_STATUS)(
            userStatus.defaultInstance.updateExpr(
              _.user:~ $("user")
            ))
          .extract(_.some)(_ saveAs "${user}"+"StatusResponse") //unique session variable for each "user"
          .sessionCombiner(SessionCombiner.pick("${user}"+"StatusResponse")) //unique session variable for each "user"
          .header(SessionHeader)($("userSessionId"))
          .endCheck(statusCode is Status.Code.OK)
      )
  }
```

And Later same stream name can be used for reading notification information of a user
```
grpc("Get User Status")
        .serverStream("${user}"+streamName)
        .copy(requestName = "Reconciliate")
        .reconciliate

```

**Additional context**
Is there any temporary solution or suggestion for the above request. I do believe there are some gatling level standards that we can't change

**Comment by phiSgr** [comment]
> I would like to call same sever stream multiple times by providing following things as unique from a single gatling virtual user 

Could you describe what's stopping you from using multiple virtual users for your use case?

> `.extract(_.some)(_ saveAs "${user}"+"StatusResponse") //unique session variable for each "user"`
> I do believe there are some gatling level standards that we can't change

Indeed I cannot make `saveAs` in Gatling take a dynamic attribute name.

---

Although the Gatling DSL does not afford all the dynamic behaviour you need, you can always use the host language, Scala. For example:

```scala
exec((1 to 100).map { id =>
  exec(
    grpc("Get User Status")
      .serverStream(s"stream$id") 
      .start(...
  )
})
```

This should start 100 streams.

**Comment by UserNoOne** [comment]
Yeah, As per my backend architecture. Admin user need to know status of other users. So, one virtual user acts like a admin user and subscribe to user status notifications of remaining users

**Comment by phiSgr** [comment]
Load test aside, I suggest changing that to allow admin to listen to all users with one single stream.

---

If the snippet I provided works for you, please close the issue.

**Comment by UserNoOne** [comment]
Yes, that design is in progress on backend :) Will close the issue in few hours 👍
