### ISSUE TITLE
can't make a class with a package that matches option java_package in proto file

### ISSUE THREAD

**Issue by cozima0210** [phiSgr/gatling-grpc#46]
Hi @phiSgr, I am using this repository to have a load testing with application with akka-grpc.
I want to know how it generate a class with a package that matches option java_package in proto file.
Could you please pull a repository below and confirm it?
https://github.com/cozima0210/akka-grpc-sample
When you compile this project using `sbt compile`, you can see the issue by comparing two files below.

- gatling/target/scala-2.13/src_managed/main/sample/grpc/sample/SampleRequest.scala
```scala
// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package sample.grpc.sample

@SerialVersionUID(0L)
final case class SampleRequest(
```
- server/target/scala-2.13/akka-grpc/main/sample/grpc/SampleRequest.scala
```scala
// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package sample.grpc

@SerialVersionUID(0L)
final case class SampleRequest(
```
I think those files are gererated by same proto file, which is `server/src/main/protobuf/sample.proto`.
```proto
option java_package = "sample.grpc";
```
In the proto file, I defined the java_package is `sample.grpc`. So I think the generated SampleRequest class under `gatling/target` is not correct package, whick is `sample.grpc.sample`.
Could you please let me know how to solve this? Thanks.

**Comment by phiSgr** [comment]
https://github.com/akka/akka-grpc/blob/v1.1.1/sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala#L83

This line is probably the reason.

---

I don't get why you want to generate code for the `gatling` subproject, as it already `dependsOn` the `server` transitively and can use its classes.

---

This is not related to Gatling/Gatling-gRPC at all. This is a code generation problem. You should have been asking the ScalaPB team.
Asking this question on StackOverflow tagging [gatling](https://stackoverflow.com/questions/tagged/gatling) is fine. But asking on a issue board, which forbids questions, is not OK.

**Comment by cozima0210** [comment]
@phiSgr I solved it! Thaks a lot!!
