### ISSUE TITLE
Support for application/grpc-web+[proto, json, thrift]

### ISSUE THREAD

**Issue by UserNoOne** [phiSgr/gatling-grpc#47]
**Is your feature request related to a problem? Please describe.**
load test a web server that runs on **grpc-web+[proto, json, thrift]** https://github.com/grpc/grpc-web

**Describe the solution you'd like**
we can use  "scalapb-grpcweb" for generating Scala sources needed to implement clients for gRPC-web (similar to "scalapb-runtime-grpc")
Similar structure/template that was used for supporting gRPC over http/2.0 i.e 
```
  grpc("Requests 1")
      .rpc(GrpcWeb.METHOD_AUTH)
      .payload(
        AuthRequest(
          email = "sample@gmail.com"
        )
      )
      .header(ReqIdHeader)(Random.alphanumeric take 30 mkString "")
```

**Comment by phiSgr** [comment]
This requires translating the gRPC action builder to an HTTP action builder, and on top of it, a gRPC-web frame parser. I will work on it but no ETA can be given.

Contribution welcome.

**Comment by UserNoOne** [comment]
Awesome! Any specific links your were referring for it apart form grpc-web

**Comment by phiSgr** [comment]
I'm talking about porting [this file](https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/grpcwebstreamparser.js).

**Comment by UserNoOne** [comment]
btw, this [example ](https://github.com/envoyproxy/envoy/blob/main/examples/grpc-bridge/client/client.py) in python helped me to simulating a call towards my envoy proxy(that translates grpc-web to gRPC) 

just needs to add content type as 'application/grpc-web+proto' in header and need to pack data like below
```
from struct import pack
import requests

payload = AuthReq(
        Email="sample@ea.com",
        redirectUri="users-login-page/login",
        pass = "$%FDGD"
    )

HEADERS = {
    'content-type': 'application/grpc-web+proto',
}

data = protoReq.SerializeToString()
data = pack('!cI', b'\0', len(data)) + data
resp = requests.post(envoyProxy+ "/server.authentication/auth", data=data, headers=HEADERS)
```
May be similar thing can be done in Scala ?

**Comment by UserNoOne** [comment]
Finally able to trigger request from Gatling/Scala towards envoy proxy by following procedure mentioned in [link ](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_http1_bridge_filter)

```
**The body should be the serialized grpc body which is:**
1 byte of zero (not compressed).
network order 4 bytes of proto message length.
serialized proto message.
```

```
payload = AuthReq(
        Email="sample@ea.com",
        redirectUri="users-login-page/login",
        pass = "$%FDGD"
    )

val bytes = payload .toByteArray
val length = intToNetworkByteOrder(bytes.length)
var data = new Array[Byte](bytes.length + 5)
data(0) = '\u0000'.toByte
System.arraycopy(length, 0, data, 1, length.length)
System.arraycopy(bytes, 0, data, 5, bytes.length)

def intToNetworkByteOrder(num: Int): Array[Byte] = {
    var localNum = num
    val buf = new Array[Byte](4)
    for (i <- 3 to 0 by -1) {
      buf(i) = (localNum & 0xff).toByte
      localNum >>>= 8
    }
    buf
  }
```

And finally above **data** variable is used in Gatling http request body
