### ISSUE TITLE
Retry Stream Connection

### ISSUE THREAD

**Issue by UserNoOne** [phiSgr/gatling-grpc#48]
**Is your feature request related to a problem? Please describe.**

Often ALB's or backend close/terminate established streaming connections by sending RST_STREAM 
`08:12:11.944 [DEBUG] i.g.n.NettyClientHandler - [id: 0x73fb85e6,-  INBOUND RST_STREAM: streamId=3 errorCode=2 `
when configured idle timeout reached.  

```
gRPC stream completion:
status=
INTERNAL, description: HTTP/2 error code: INTERNAL_ERROR
Received Rst Stream
```

**Describe the solution you'd like**
A way to re-try streaming connection again if closed or a way to delete session variable
 ` serverStreamBucketList -> com.github.phisgr.gatling.grpc.stream.ServerStreamCall@3709bcf0,` when connection terminated by some reason.  So that client can re-try if session variable doesn't exists

**Additional context**
Any quick suggestion to get handle this case ?

**Comment by UserNoOne** [comment]
@phiSgr can I get any help to quickly add gRPC stream re-connection logic?

**Comment by mxndtr** [comment]
@phiSgr I have the same problem. If the connection is broken, then vUser is not disconnected.
Maybe you can add a stream status check.

**Comment by phiSgr** [comment]
When the stream call ends, the stream is removed from the virtual user session.

```
doIf("${myStreamName.isUndefined()}") {
  // reconnect logic
}
```

**Comment by shashi7893** [comment]
@phiSgr Above logic doesn't quite work for me. I put my server streaming calls in the doIf and could see an increase in subscribers count over time. I have also tried checking if I have a status code from the server and then do a reconnect. This also resulted in a similar behavior. I'm reading if I have a response from the server stream using 
`      exec(
        grpc(requestName)
          .serverStream(method,streamName)
          .copy(requestName = requestName)
          .reconciliate
      )`
