### ISSUE TITLE
Send requests to multiple endpoints

### ISSUE THREAD

**Issue by muyang-w** [phiSgr/gatling-grpc#49]
**Is your feature request related to a problem? Please describe.**
I'd like to send requests to multiple methods within one test by adjusting the methodDescriptor that gets passed into the .rpc() method. The test I'm running is based off of real user logs, and I can transform these logs into a TSV of the relevant fields and use this file as the feeder. I'm able to get each method name into the feeder.

This is what the code looks like with one constant method:
```
feed(perfLog)
                    .exec { session => {
                        /*
                        	Some fun session stuff
                        */
                    }
                    }
                    .exec {
                        var call = grpc("""${requestName}""")
                            .rpc(method)
                            .payload("""${modifiedRequestBody}""")
                        // Hacky stuff
                        call
                    }
```

**Describe the solution you'd like**
I would like to be able to use the EL to pass in a dynamically generated method to the .rpc() call, so that I can mimic each real user request if they hit multiple endpoints. I'm not sure if this is possible, but ideally the .rpc() could be adjusted to also take a session.Expression[T] like .payload() does, instead of the MethodDescriptor[req, res] it requires now. The code would end up like this:
```
feed(perfLog)
            .exec { session => {
                /*
                 Some fun session stuff
                */
                val methodDescriptor: MethodDescriptor[_,_] = .....session("methodName").as[String].....asInstanceOf[MethodDescriptor[_,_]]
                session.set(METHOD_DESCRIPTOR, methodDescriptor)

            }
            }
            .exec {
                var call = grpc("""${requestName}""")
                    .rpc("""${methodDescriptor}""")
                    .payload("""${modifiedRequestBody}""")
                // Hacky stuff
                call
            }
```

**Describe alternatives you've considered**
In terms of dynamically-generating methods, not much has worked. I've tried grabbing the methodName at multiple points post-feeder pre-rpc, but each has resulted in compiler/runtime errors, which leads me to...

**Additional context**
A feature would be amazing; a temporary workaround is greatly appreciated. There's a part of me that thinks Gatling itself may be the culprit, but I'm hoping that's not the case since this library has been extremely helpful.

**Comment by phiSgr** [comment]
Work around:
Use this to run arbitrary code as a Gatling request action. Less support and integration, but at least you can get your work done.
https://github.com/phiSgr/gatling-ext/blob/master/src/main/scala/com/github/phisgr/gatling/generic/Predef.scala#L31

I've never imagined that the RPC itself can be dynamic. This seems to be a very niche use case that I don't think I'll build a feature for.

**Comment by muyang-w** [comment]
Thanks for the answer! I don't mean to turn this into Q&A but I'm admittedly having trouble implementing the gatling-ext code. The `callbackAction` method returns a `codeActionBuilder`, which leads me to believe it would replace the grpc request code within the `exec` method since that returns a `GrpcCallActionBuilder`. Do I build the grpc request using the 
`gatling-grpc` library in `callbackAction()` along with all the other work I have to do (can I even cast from GrpcCallAB to codeAB?), or else where in the scenario would the gatling-ext code fit in? I can move this to StackOverflow if needed.

**Comment by phiSgr** [comment]
With `callbackAction` you call the generated code that takes callbacks.
https://grpc.io/docs/languages/java/generated-code/#unary-1

Or if you're using the ScalaPB generated code that returns `Future`s, use `futureAction`.

**Comment by phiSgr** [comment]
With `callbackAction`, you will have to make the call yourself without using gatling-grpc at all.

Another way is to fork and patch to make the rpc itself dynamic. I don't think much change will happen to Gatling-gRPC, so there is not much matainence risk.

**Comment by muyang-w** [comment]
Thanks a ton for the help!
