### ISSUE TITLE
How use protobuf dependency package?

### ISSUE THREAD

**Issue by thinkerou** [phiSgr/gatling-grpc#5]
Now proto file are placed in `/src/test/protobuf` dir, but I want to use protobuf dependency package, how do it?
thanks!

**Comment by phiSgr** [comment]
Do you mean you have a jar that contains `.proto` files and want [ScalaPB](https://github.com/scalapb/ScalaPB) to compile them? This question is probably for [them](https://gitter.im/trueaccord/ScalaPB?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) then.

That said, have you tried having the configurations for both `Compile` and `Test`?

```
PB.targets in Compile := Seq(
  scalapb.gen() -> (sourceManaged in Compile).value
)
PB.targets in Test := Seq(
  scalapb.gen() -> (sourceManaged in Test).value
)
```

**Comment by thinkerou** [comment]
@phiSgr thanks!
