### ISSUE TITLE
Support for Gatling 3.7

### ISSUE THREAD

**Issue by rene-m-hernandez** [phiSgr/gatling-grpc#57]
It would seem the last release of gatling-grpc is incompatible with Gatling 3.7. At a minimum (likely there are more?), this error occurs:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/gatling/core/check/FindCheckBuilder
	at com.github.phisgr.gatling.grpc.check.GrpcCheckSupport.$init$(GrpcCheckSupport.scala:11)
	at com.github.phisgr.gatling.grpc.Predef$.<clinit>(Predef.scala:5)
	at com.github.phisgr.gatling.grpc.Predef.grpc(Predef.scala)
```

Which seems to be caused by a refactor of the CheckBuilder class from [3.6](https://github.com/gatling/gatling/blob/3.6/gatling-core/src/main/scala/io/gatling/core/check/CheckBuilder.scala#L28) to [3.7](https://github.com/gatling/gatling/blob/3.7/gatling-core/src/main/scala/io/gatling/core/check/CheckBuilder.scala#L33).

This is a feature request to have support for 3.7; I was hoping to use the new Gatling Java API if possible.

**Comment by yeenow123** [comment]
@rene-m-hernandez Should this library work smoothly with the Gatling Java API?  Primary reason for us to switch to 3.7 is to migrate over to Java/Kotlin APIs

**Comment by rene-m-hernandez** [comment]
Java bindings do not exist as they day for the base Gatling library; however, I believe it should work using some of the provided Expression bindings and creating a couple of Java classes to wrap some gatling-grpc code. I was not able to fully test due to this bug.

**Comment by phiSgr** [comment]
After I get the time to finish upgrading to Gatling 3.7. I will create Java bindings.

**Comment by phiSgr** [comment]
Closed by 377fadc

**Comment by phiSgr** [comment]
@yeenow123 
For Kotlin/Java support, see #58

**Comment by rene-m-hernandez** [comment]
Thank you!
