### ISSUE TITLE
Allow Checking the State of a Client Stream

### ISSUE THREAD

**Issue by jGleitz** [phiSgr/gatling-grpc#60]
**Is your feature request related to a problem? Please describe.**
Our application uses client and bidi streams. These streams are sometimes (expectedly) terminated by the server. In our load test, we want to re-establish the streams as soon as we notice that they have been terminated.

**Describe the solution you'd like**
The re-establish behaviour is difficult to implement in Gatling to begin with, mainly because branching out in one user’s session is still not possible. However, in our case, we can probably get away with just checking the stream state before sending the next message, re-establishing it if necessary. There’s a race condition there if the server terminated, but we have not yet noticed. However, we can address that.

To allow this solution, the easiest fix would be to make `StreamCall.state` public. With some housekeeping, we could access it and check it in a Gatling `doIf` block. An even nicer solution would be to expose the `state` on `BidiStream` and `ClientStream` (and, for good measure, probably also on `ServerStream`). This would make using the state in the DSL easier.

**Describe alternatives you've considered**
Providing some way of registering callbacks for stream events. However, it would be quite complicated to support Gatling’s DSL there. The solution would also be unnecessarily complex for our use case.

**Comment by phiSgr** [comment]
Hopefully I can release it this week.
