### ISSUE TITLE
Allow Extracting Different Kinds of Events From Streams

### ISSUE THREAD

**Issue by jGleitz** [phiSgr/gatling-grpc#62]
In our application, we can put the messages that we receive over streams into different categories. We’d like to measure the delays for each category separately. 

To address this, it would be great to have something like an `eventExtractor`. It would work like the current `timestampExtractor`, except that it would allow influencing all the other parameters that are sent to Gatling’s `logResponse`. For our use case, we mainly want to change the `requestName` that is being reported. But I think while we are on it, we should also allow changing the `scenario`, `groups`, `status`, `code`, and `message`.

I think this change can be implemented backward compatible, the exsting `timestampExtractor` would just delegate to the new `eventExtractor`

**Comment by phiSgr** [comment]
How do you envision this change to play with the stream checks?

**Comment by jGleitz** [comment]
I think the checks would need to consult the event extractor as well to know how to report failures.

**Comment by phiSgr** [comment]
🤔🤔🤔🤔🤔

I don't have a good understanding of your use case to dream up an API. (TBH that was pretty much how I felt when I was designing the streaming checks.)

If you can suggest an API I will happily look into implementing it.

**Comment by jGleitz** [comment]
Sure, here is my proposal.

Let us construct an example: We want to test a bidi stream that represents an order system of some sort: We send orders upstream, and get updates about the order downstream. Orders can be received, in process and completed. In our load test, we now want to see the response times separated by type: The time between ordering and the ‘received message’, the time between ordering and the first ‘in process’ update, and the time between ordering and the ‘completed’ notification.

<details>
<summary>Proto File for the example API</summary>

```proto
service Orders {
  rpc orders(stream Order) returns (stream OrderStatus);
}

message Order {
  string id = 1;
  string content = 2;
}

message OrderStatus {
  string id = 1;
  oneof status {
    /** Always true **/
    bool received = 2;
    /** Indicates how far processing is **/
    float processedShare = 3;
    string completionResult = 4;
  }
}
```

</details>

With the current API, we cannot report the response types separated by type. To facilitate this, we introduce the new class `StreamResponse`, which allows declaring the `sendTimestamp`, `responseName`, `scenario`, `groups`, `status`, `responseCode` and `message` of every response. Of those fields, only the `timestamp` is mandatory, with the convention that whatever other field is not set will default to the values that were set when opening the stream.

<details> 
<summary>The <code>StreamResponse</code> class</summary>

```scala
package com.example

import io.gatling.commons.stats.{Status, OK, KO}

case class StreamResponse private(
    val sendTimestamp: Long,
    private val responseName: Option[String] = None,
    private val scenario: Option[String] = None,
    private val groups: Option[List[String]] = None,
    private val status: Option[Status] = None,
    private val responseCode: Option[String] = None,
    private val message: Option[String] = None,
    private val reportOnlyOnFailure: Boolean = false
) {
    def this(sendTimestamp: Long) = this(sendTimestamp)

    /**
     * Sets the response name to report for this event. If not set, the name will be the request name of the stream.
     */
    def responseName(responseName: String): StreamResponse = copy(responseName = Some(responseName))

    /**
     * Sets the scenario to report for this event. If not set, the scenario will be the one that opened the stream.
     */
    def scenario(scenario: String): StreamResponse = copy(scenario = Some(scenario))

    /**
     * Sets the groups to report for this event. If not set, the groups will be the ones from the step that opened the stream.
     */
    def groups(groups: List[String]): StreamResponse = copy(groups = Some(groups))

    /**
     * Sets the status to report for this event. If not set, the status will be [[OK]] iff no checks failed, and [[KO]] iff at least
     * one check failed for the message of this event.
     */
    def status(status: Status): StreamResponse = copy(status = Some(status))

    /**
     * Sets the response code to report for this event. If not set, no response code will be reported.
     */
    def responseCode(responseCode: String): StreamResponse = copy(responseCode = Some(responseCode))

    /**
     * Sets the message to report for this event. If not set, no message will be reported.
     */
    def message(message: String): StreamResponse = copy(message = Some(message))    
    /**
     * Specifies that this response will only be reported if some check failed.
     */
    def reportOnlyOnFailure: StreamResponse = copy(onlyOnFailure = true)
}
```

</details>

Users of this library can define a `streamResponseExtractor` on server and bidi streams, which, given a message and the current session, has to return a `StreamResponse`. This looks exactly like the `TimestampExtractor`.

<details>
<summary>The <code>StreamResponseExtractor</code></summary>

```scala
package com.example

import io.gatling.core.session.Session

trait StreamResponseExtractor[-Res] {
    /**
     * @param session The session of the streaming branch.
     * @param message The message received from the streaming call
     * @param streamStartTime The start time of this stream
     *
     * @return A stream response for this message, indicating how it should be logged.
     * [[StreamResponseExtractor.IgnoreMessage]] if this message should not be logged.
     */
    def extractResponse(session: Session, message: Res, streamStartTime: Long): StreamResponse
}

object StreamResponseExtractor {
    /** Return this sentinel value and the message will not be logged */
    final val IgnoreMessage: StreamResponse = null

    final val IgnoreAllMessages: StreamResponseExtractor[Any] = (_, _, _) => IgnoreMessage
}
```

</details>

This is almost it. However, I suggest adding one more helper: An easy way to write down the timestamp of messages that are being sent. Currently, this timestamp is hard to get: Our best idea was to have a Gatling `Action` directly before sending the message, which can access the Gatling clock. However, this will be somewhat off. This library has already access to the send timestamp. If it offered a way to give it back to users, implementing everything would be a lot easier.

I suggest adding a `sendTimestampCallback` to `StreamSendBuilder`. It would simply be defined as

```scala
def sendTimestampCallback(callback: (timestamp: Long, request: Req, session: Session) => Unit): StreamSendBuilder[Req]
```

With all that, let’s write an example load test to see the API in action.

<details>
<summary> Imports </summary>

```scala
package com.example

import com.example.proto.{Order, OrdersGrpc}
import com.github.phisgr.gatling.grpc.Predef._
import io.gatling.commons.validation.Failure
import io.gatling.core.Predef._

import java.util.concurrent.ConcurrentHashMap
import java.util.{Collections, UUID}
import scala.collection.concurrent.TrieMap
import scala.concurrent.duration._
import scala.language.postfixOps
```

</details>

```scala
class OrderSimulation extends Simulation {
    private val orderStream = grpc("Order Stream")
        .bidiStream("Order Stream")
    private val orderTimestamps = new TrieMap[String, Long]()
    private val startedOrders = Collections.newSetFromMap[String](new ConcurrentHashMap())

    setUp(
        scenario("Orders")
            .exec(
                orderStream.connect(OrdersGrpc.getOrdersMethod)
                    .responseExtractor((_, message, _) =>
                        message match {
                            case m if m.hasReceived => 
                                new StreamResponse(orderTimestamps(message.getId)).responseName("Order Received")
                            case m if m.hasProcessedShare && startedOrders.add(message.getId) =>
                                new StreamResponse(orderTimestamps(message.getId)).responseName("Order Processing Start")
                            case m if m.hasProcessedShare => 
                                new StreamResponse(orderTimestamps(message.getId)).responseName("Order Processing Update").reportOnlyOnFailure
                            case m if m.hasCompletionResult =>
                                startedOrders.remove(message.getId)
                                new StreamResponse(orderTimestamps.remove(message.getId).get).responseName("Order Completed")
                        }
                    )
                    .extract(_.getId.some)(_ validate("starts with o", (id, _) => id match {
                        case good if good.exists(_.startsWith("o")) => good
                        case bad => Failure(s"does not start with 'o': $bad")
                    }))
            )
            .repeat(100) {
                exec(orderStream.send(Order.newBuilder().setId("o" + UUID.randomUUID()).build())
                    // In this case, we could wire the ID directly through. But the value could be coming from the session,
                    // in which case we would extract it here.
                    .sendTimestampCallback((time, request, _) => orderTimestamps.put(request.getId, time)))
            }
            .exec(orderStream.complete(waitFor = StreamEnd))
            .inject(constantUsersPerSec(5) during (1 minute))
    )
}
```

To understand the semantics of the proposed API, let us state what we expect to be reported by this test:
 1. The total runtime of the stream, together with the response code, and potential `endCheck` failures, will be reported under the response name ‘Order Stream’
 2. The time between the order and the respective `OrderStatus` update will be reported under the appropriate name (i.e. either `Order Received`, `Order Processing Start`, or `Order Completed`). The scenario and groups will be the same as for the stream (since we didn’t change them – but we could have!)
 3. If the `"starts with o"` check fails for any message, it will be reported under the appropriate name. In particular, if a later processing update fails the check, it _will_ be reported under `Order Processing Update`, even though the message would not have been reported had it passed the check.

This design would fit our use case well and is, hopefully, flexible enough for most other user cases. What do you think?

**Comment by phiSgr** [comment]
Taking some user code, which creates some pointerful objects, which instruct what library code should do, seems inelegant.

Let me just give you all the flexibility you need. 🤣

**Comment by jGleitz** [comment]
Hi @phiSgr, I finally got around using your change. Works like a charm for us! Any I agree, for such an advanced use case, it makes sense to just give us access to the Gatling API.
