### ISSUE TITLE
Not compatible with gatling 3.8.4

### ISSUE THREAD

**Issue by kpritam-tw** [phiSgr/gatling-grpc#64]
Latest version of `gatling-grpc` `v0.13.0` is not compatible with `gatling-core` `v3.8.4`.

I see main branch is already using `gatling-core` `v3.8.4`, any plans for publishing latest main of this library?

**Comment by ajax-osadchuk-r** [comment]
@phiSgr I also would like to use your library. Could you please clarify whether there are any plans to support gatling 3.8.+ in near times?

**Comment by phiSgr** [comment]
Released
