### ISSUE TITLE
Cannot cast value of type 'io.grpc.examples.routeguide.RouteSummary' to type 'byte[]'

### ISSUE THREAD

**Issue by Mirontsev** [phiSgr/gatling-grpc#68]
When I use ClientStream and a response looks like

point_count: 5
feature_count: 5
elapsed_time: 7

The action
https://github.com/phiSgr/gatling-grpc/blob/a93ee9f0e0031fc287cce1edad84fa3496dbaf77/src/main/scala/com/github/phisgr/gatling/grpc/util/package.scala#L122
throw the exception
`
Cannot cast value of type 'io.grpc.examples.routeguide.RouteSummary' to type 'byte[]'
`

Step to reproduce:

1. Run the docker image **docker pull dmitriysmol/grpc-mock:1.1** and share port 9001
2. Perform a simulation for the class from an archive
3. Proto file is in the archive
[githubissue.zip](https://github.com/phiSgr/gatling-grpc/files/9926782/githubissue.zip)

Dependencies
 ```
lazy val gatling: Seq[ModuleID]          = Seq(
    "io.gatling.highcharts" % "gatling-charts-highcharts",
    "io.gatling"            % "gatling-test-framework",
  ).map(_ % "3.8.4" % Test)

lazy val janino: Seq[ModuleID] = Seq("org.codehaus.janino" % "janino" % "3.1.8")
 
lazy val epoll: Seq[ModuleID] = Seq(
    "io.netty" % "netty-transport-native-epoll"  % "4.1.65.Final" classifier "linux-x86_64",
    "io.netty" % "netty-transport-native-kqueue" % "4.1.65.Final" classifier "osx-x86_64",
  )

  lazy val gatlingGrpc: Seq[ModuleID]        = Seq("com.github.phisgr" % "gatling-grpc" % "0.15.0" % "test")
  lazy val gatlingGrpcExample: Seq[ModuleID] = Seq("io.grpc" % "grpc-examples" % "0.15.0")

  lazy val grpcDeps: Seq[ModuleID] = Seq(
    "io.grpc"               % "grpc-netty"           % scalapb.compiler.Version.grpcJavaVersion,
    "com.thesamet.scalapb" %% "scalapb-runtime-grpc" % scalapb.compiler.Version.scalapbVersion,
    "com.thesamet.scalapb" %% "scalapb-runtime"      % scalapb.compiler.Version.scalapbVersion % "protobuf",
  )
```

**Comment by phiSgr** [comment]
Well that was an embarrassing mistake. I will publish a patch this weekend.

Fro now, use `grpc(managedChannelBuilder...).forceParsing` to work around.

**Comment by Mirontsev** [comment]
Work around didn't solve the issue. The test goes to this string, we receive an error and test has never stopped.

**Comment by Mirontsev** [comment]
Logger must be enabled in logback.xml
<logger name="com.github.phisgr.gatling.grpc" level="TRACE" />
When I disabled the logger, the run was done successfully
