### ISSUE TITLE
Ignore If stream message is read once

### ISSUE THREAD

**Issue by UserNoOne** [phiSgr/gatling-grpc#70]
**Not able to figure it out whether a stream message is already read or not** 
Gatling actor subscribe to some "x" server stream notification and added extract/session-combiner to save server stream notification at make available to main session. After that able to read stream message with the help of "reconciliate". Example: https://github.com/phiSgr/gatling-grpc/blob/master/src/test/scala/com/github/phisgr/example/StreamingExample.scala#L62

**A way to ignore a stream message if it already read with reconciliate or way to delete server stream RPC session variable in streaming session**

Any quick way to solve this will be helpful

**Comment by phiSgr** [comment]
You can set `sync = true` in [`reconciliate`](https://github.com/phiSgr/gatling-grpc/commit/a56d9de763165a0a073649ee8fb3dc8ef80001c7#diff-aa546482611253cbe761ec584517b84644fdf9693618267f4ad9d31f9a03a6a8R52) in `0.17.0`.

Then in the `SessionCombiner` you can "move" the attribute to another name. If the name you `saveAs` is populated again, it's not read.

Sorry that took almost a year.
