### ISSUE TITLE
Unable to use with Java

### ISSUE THREAD

**Issue by cristianbriscaru-worldremit** [phiSgr/gatling-grpc#74]
**Describe the bug**
I am unable to use this plugin with java, not sure if I am missing something or if there is a bug in the plugin .
I am getting the fallowing errors:
1) `grpc("GrpcAction")`  error : Cannot resolve method 'grpc(String)'
2) `scenario("Grpc").exec(grpcAction)`  error : Cannot resolve method 'exec(GrpcCallActionBuilder<Ping, Pong>)'
3) `setUp(...).protocols(grpcConf)` error : Cannot resolve method 'protocols(StaticGrpcProtocol)'

**To Reproduce**
clone this reproduction repo https://github.com/cristianbriscaru-worldremit/gatling-grpc-gradle-demo 
build the project `./gradlew build` and then go to `/src/gatling/java/com/github/phisgr/exampletest/java/PingPongSimulationJava`
and you can see you can't use this plugin for Java and you get the fallowing errors:

1) `./grpc("GrpcAction")`\  error : Cannot resolve method 'grpc(String)'
2) `scenario("Grpc").exec(grpcAction)`\  error : Cannot resolve method 'exec(GrpcCallActionBuilder<Ping, Pong>)'
3) `setUp(...).protocols(grpcConf)`\ error : Cannot resolve method 'protocols(StaticGrpcProtocol)'

**Expected behavior**
To be able to use this plugin with Java

**Environment:**
 - OS: macOS Ventura 13.2
 - Java: result of 11 
 - 'io.gatling.gradle' version "3.8.4"  or "3.9.0.2"
 - 'com.github.phisgr:gatling-javapb:1.3.0'
 - 'com.github.phisgr:gatling-grpc:0.15.1'

**Additional context**
Reproduction repo https://github.com/cristianbriscaru-worldremit/gatling-grpc-gradle-demo

**Comment by phiSgr** [comment]
To writing the test in Java, you need the [gatling-grpc-kt](https://github.com/phiSgr/gatling-grpc/tree/master/gatling-grpc-kt) wrapper.

https://search.maven.org/artifact/com.github.phisgr/gatling-grpc-kt/0.15.1/jar
