### ISSUE TITLE
Support for BiDi Stream Authentication Headers

### ISSUE THREAD

**Issue by hillnicole1107** [phiSgr/gatling-grpc#75]
Is it possible to pass in headers to the grpc bidiStream?

I have tried calling header and headerEl on the stream. Is there another way to pass in headers on initial method invocation?

Ex. simulation:
class BiDiStreamingSimulation extends Simulation {
  val bidiCall = grpc("BiDi call").bidiStream("bidi")

  val scn = scenario("BiDi streaming")
    .exec(bidiCall.header("Ocp-Apim-Subscription-Key", "ex. key"))
    .exec(bidiCall.connect(SpeechConversationServiceGrpc.METHOD_CONNECT)
      .endCheck(statusCode is Status.Code.OK))
    .exec(bidiCall.send(ConversationInputMessage("Gatling Load Test First")))
    .exec(bidiCall.complete)

  setUp(scn.inject(rampUsersPerSec(1) to (2) during (20 seconds)).protocols(grpcPsgConf.shareChannel))
}

**Comment by hillnicole1107** [comment]
Sorry for the lack of details I am very new to open source projects.

For future reference where do I ask questions? 
Thanks

**Comment by phiSgr** [comment]
https://github.com/phiSgr/gatling-grpc/blob/master/.github/ISSUE_TEMPLATE/question.md
