### ISSUE TITLE
Version support could use some clarity

### ISSUE THREAD

**Issue by pluttrell** [phiSgr/gatling-grpc#76]
The README mentions

> Java/Kotlin API
>
> Since 3.7, Gatling adds Java API for the test to be written in Java or Kotlin. Since Gatling-gRPC 0.14.0, [a binding](https://github.com/phiSgr/gatling-grpc/blob/master/gatling-grpc-kt) is written in Kotlin for Java and Kotlin users.

But this [demo](https://github.com/phiSgr/gatling-grpc-sbt-demo) shows it working with `3.4.1`. See [build.sbt](https://github.com/phiSgr/gatling-grpc-sbt-demo/blob/7b5ea5eb246583304fca12909a0233bc952edd9d/build.sbt#L9).

**Comment by phiSgr** [comment]
There is currently not a demo for the new Kotlin/Java support.

Also the SBT plugin for Gatling doesn't support tests written in Kotlin/Java.

**Comment by phiSgr** [comment]
Link to demo for Kotlin support added in 72ad2f6.
