### ISSUE TITLE
Error: Caused by: java.lang.UnsupportedOperationException: There were no requests sent during the simulation, reports won't be generated

### ISSUE THREAD

**Issue by farasool** [phiSgr/gatling-grpc#83]
package performance
 import io.gatling.core.scenario.Simulation
 import io.gatling.core.Predef._
 import com.intuit.karate.gatling.PreDef._
 import io.gatling.http.Predef._
 import scala.concurrent.duration._

 class PerformanceRunner extends Simulation{
 val protocol = karateProtocol()
   protocol.nameResolver = (req, ctx) => req.getHeader("Scenario")
   System.setProperty("karate.appName", "test");
   System.setProperty("karate.env", "t1");
   System.setProperty("threads", "1");
       
   val concurrentUsers = Integer.getInteger("concurrent.users", 1).toInt

   val a = scenario("abc").exec(karateFeature("classpath:Sems/performance/a.feature"))
   val b= scenario("bcd").exec(karateFeature("classpath:Sems/performance/b.feature"))
   val c= scenario("cde").exec(karateFeature("classpath:Sems/performance/c.feature"))
   val d= scenario("def").exec(karateFeature("classpath:Sems/performance/d.feature"))
   
   setUp(
     a.inject(constantConcurrentUsers(concurrentUsers) during (1 minutes)),
     b.inject(constantConcurrentUsers(concurrentUsers) during (1 minutes)),
     c.inject(constantConcurrentUsers(concurrentUsers) during (1 minutes)),
     d.inject(constantConcurrentUsers(concurrentUsers) during (1 minutes)),

   ).protocols(protocol)
 }

**Comment by phiSgr** [comment]
I don't see any of my code. What does this have to do with me?

Even if you do think the error you see is a bug of my library, you still have to fill out the information required in the issue template.
