### ISSUE TITLE
Use flatbuffers library instead of protobuf

### ISSUE THREAD

**Issue by Orhan2014** [phiSgr/gatling-grpc#85]
Hello, i want to use gatling to send flatbuffers messages over gRPC.
Does your plugin support the transmission of FlatBuffer messages via gRPC, and do you have any sample examples or documentation available to demonstrate this functionality

**Comment by phiSgr** [comment]
My code is built on grpc-java. It should work generically as long as there's the `Marshaller` for it.

Give it a try and let me know how it goes. Good luck.
