### ISSUE TITLE
Streaming sharing for Users

### ISSUE THREAD

**Issue by nptri** [phiSgr/gatling-grpc#87]
**Is your feature request related to a problem? Please describe.**
I have a use case where I have to use Throttle on a server Streaming (in short: SS), this SS will be completed itself once the REST API after that is called, when I add in throttling, it would cause the SS to stay alive (or other term, which I'm not sure) and avoid next user to initiate a new stream for itself and it would return as "Unable to create a new server stream with name: already exists"

**Describe the solution you'd like**
Some possible solutions that linger my mind as:
+ Add a complete method that sends response time to Gatling and mark the stream to be done
+ Restructure SS method to allow random name initiated (as I am aware, the current SS method will use the same name throughout test run, thus making it to be blocked for the next User with stream)
+ Allow sharing channel for streaming (current example does not have streaming throttling so I hope this is implemented)

**Describe alternatives you've considered**
As described above, the stream will be completed as OK status itself, but I have to kill it again using cancelStream, only by that then the workflow will be running normally, but the record for time response of this stream will not appeared on Gatling.

**Comment by phiSgr** [comment]
I don't understand the problem you're trying to solve. While I could ask clarifying questions and comment on some points, I'm opting not to.

I understand the challenges you face as a non-native English speaker. But for the sake of my sanity, I can no longer attempt to decipher your problem from your writing.

**Comment by phiSgr** [comment]
I wish you luck in getting help.

**Comment by nptri** [comment]
Hi @phiSgr , let me break it down into step-by-step pseudo-code as below
`
for (user = 1, user <= 50, user++){
  exec(serverStream)
  while (serverStream is Running){
      exec (REST)
      return (serverStream is OK) and return (serverStream response_time)
  }
}
)
`
Hope with this pseudo-code, you get what I'm expecting.
Please refer to this similar issue [here](https://stackoverflow.com/questions/74721185/how-can-i-create-multiple-server-streams-for-a-single-user-in-gatling-grpc-load)
Again, in pseudo-code, the behavior I am getting is:
`
  exec(serverStream)
  while (serverStream is Running){
      exec (REST)
      return (serverStream is OK) and return (serverStream response_time)
            Exception_throw("Unable to create a new server stream with name: already exists")
  }
`
As pseudo code above I hope you get what I meant, with due respect, I also hurt my brain these days a lot.
If this pseudo code can clear your deciphering, please let me know and I will continue, else you can just close this topic.
